# ---------------------------------------------------------------------------
# nearmiss — Makefile
#
# The dataset and the analysis are the product, not an app. These targets are
# the operator surface for the architecture stages described in the README:
#
#   intake.py -> pipeline/ -> exposure.py -> stats/ -> publish.py -> brief.py -> server.py
#
# Every target is .PHONY (it names a job, not a file) and self-documents via
# the trailing `##` comment that `make help` greps.
#
# Tools are invoked as `$(PYTHON) -m <tool>` so a single PYTHON override points
# the whole gate at one interpreter, e.g.:
#     make verify PYTHON=.venv/bin/python
#
# Hard-rule reminders baked into these targets:
#   HR4 (privacy): `clean` NEVER deletes data/raw/ — precise raw reports are
#                  private and gitignored, and a clean must not destroy them.
#   HR5 (reproducible): `reproduce` rebuilds the published dataset and brief
#                  from raw inputs and fails if the committed output changed.
# ---------------------------------------------------------------------------

SHELL := bash
.SHELLFLAGS := -eu -o pipefail -c

PYTHON  ?= python
PIP     ?= $(PYTHON) -m pip
PACKAGE := nearmiss
CONFIG  ?= config/davis-demo.toml
PUBLISHED_DIR := data/published

.DEFAULT_GOAL := help

.PHONY: help install lock lint type test accessibility axe security verify \
        reproduce demo publish serve bench bikemaps clean

# Real-data fetch (BikeMaps.org). Override CITY and BIKEMAPS_OUT as needed.
CITY         ?= victoria
BIKEMAPS_OUT ?= build/$(CITY)-reports.json

help: ## Show this help — every target with its description
	@echo "nearmiss — open dataset + honest analysis of road near-misses"
	@echo ""
	@echo "Usage: make <target>   (e.g. make demo, make verify PYTHON=.venv/bin/python)"
	@echo ""
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## ' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "} {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

install: ## Install the package (editable) with dev extras and pre-commit hooks
	@$(PYTHON) -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)" || { \
		echo "nearmiss requires Python 3.11+ (got $$($(PYTHON) --version 2>&1))."; \
		echo "Re-run with an explicit interpreter, e.g.  make install PYTHON=python3.12"; \
		exit 1; }
	$(PIP) install -e ".[dev]"
	-pre-commit install --install-hooks

lock: ## Generate the hashed reproducible-install lockfile (requirements.lock)
	$(PYTHON) -m piptools compile --generate-hashes -o requirements.lock pyproject.toml
	@echo "lock: wrote requirements.lock (generated; do not edit by hand)."

lint: ## Lint with ruff (style + import order + bugbear) and check formatting
	$(PYTHON) -m ruff check .
	$(PYTHON) -m ruff format --check .

type: ## Type-check with mypy --strict (config in pyproject.toml)
	$(PYTHON) -m mypy

test: ## Run pytest against synthetic fixtures with KNOWN planted-hotspot answers
	$(PYTHON) -m pytest -q

accessibility: ## Structural WCAG gate on the web UI (merge-blocking)
	$(PYTHON) tools/a11y_check.py web/index.html
	@echo "accessibility: structural checks passed."
	@echo "NOTE: CI also runs axe; full conformance also requires manual NVDA + VoiceOver"
	@echo "      review — see docs/accessibility/ACR.md (this gate is the floor, not the ceiling)."

security: ## Scan deps (pip-audit) and history for secrets (gitleaks)
	$(PYTHON) -m pip_audit --strict
	@command -v gitleaks >/dev/null 2>&1 \
		&& gitleaks detect --no-banner --redact --source . \
		|| echo "security: gitleaks not found (it is a Go binary, not a pip dep); install it to enable the secret scan. CI runs it."

axe: ## Deeper accessibility check: run axe-core against the built web page (needs node)
	cd web && npm ci && npm run axe

verify: lint type test accessibility security ## Full merge gate: lint + type + test + accessibility + security
	@echo "verify: all merge gates green (lint, type, test, accessibility, security)."

reproduce: ## HR5: rebuild every published dataset + figures + brief; fail if output changed
	$(PYTHON) -m $(PACKAGE) run --config $(CONFIG) --out build/brief.md
	$(PYTHON) -m $(PACKAGE) figures --config $(CONFIG)
	$(PYTHON) -m $(PACKAGE) run --config config/riverside-demo.toml --out build/riverside-brief.md
	$(PYTHON) -m $(PACKAGE) figures --config config/riverside-demo.toml
	git diff --exit-code -- $(PUBLISHED_DIR)
	@echo "reproduce: all published datasets and figures regenerated byte-for-byte from raw inputs."

demo: ## Demonstrability: run the full pipeline over fixtures and render a sample brief
	@mkdir -p build
	$(PYTHON) -m $(PACKAGE) run --config $(CONFIG) --out build/demo-brief.md
	$(PYTHON) -m $(PACKAGE) analyze --config $(CONFIG)
	@echo "demo: sample brief written to build/demo-brief.md"
	@echo "      (recovers the planted hotspot seg-06 from tests/fixtures — a known answer)."

publish: ## Build the open GeoJSON + aggregated public dataset (privacy-checked)
	$(PYTHON) -m $(PACKAGE) publish --config $(CONFIG)
	@echo "publish: wrote $(PUBLISHED_DIR)/<city>.geojson + metadata."
	@echo "         HR4 check passed: no precise raw report leaked into the public artifact."

serve: ## Serve the accessible map + data view (read-only) at /web/index.html
	$(PYTHON) -m $(PACKAGE) serve --dir .

bench: ## Performance benchmark: time the pipeline + statistics on a city-scale synthetic dataset
	$(PYTHON) tools/benchmark.py

bikemaps: ## Fetch REAL near-miss reports from BikeMaps.org (CITY=victoria) into BIKEMAPS_OUT
	@mkdir -p $(dir $(BIKEMAPS_OUT))
	$(PYTHON) tools/fetch_bikemaps.py --city $(CITY) --out $(BIKEMAPS_OUT)
	@echo "bikemaps: real reports in $(BIKEMAPS_OUT) (intake schema)."
	@echo "          Next: real streets + exposure, then 'nearmiss run' — see docs/REAL-DATA.md."

clean: ## Remove build/test/cache artifacts — NEVER data/raw/ (HR4)
	rm -rf build/ dist/ web/node_modules \
		.pytest_cache/ .mypy_cache/ .ruff_cache/ \
		.coverage coverage.xml htmlcov/ notebooks/_build/
	find . -type d -name '__pycache__' -prune -exec rm -rf {} +
	find . -type d -name '*.egg-info' -prune -exec rm -rf {} +
	@echo "clean: build and cache artifacts removed."
	@echo "       data/raw/ (private precise reports) and $(PUBLISHED_DIR) left untouched."
