"""Property and metamorphic tests for the spatial-statistics core (FIX-14).

The exact-value guards in ``test_stats_numerics.py`` pin a single hand-computable
arrangement; these tests instead assert *invariants that must hold for every*
input — the metamorphic relations (scale/shift/permutation invariance) and the
structural guarantees of the confidence intervals — across a wide swath of
randomized inputs generated by Hypothesis. Together they catch bugs that a
fixed known-answer test cannot: an interval method that only misbehaves at a
particular count, or a cancellation error that only bites at a particular scale.

Strategies are small and bounded (finite floats, 2-30 points) and the deadline
is disabled so a slow first example never turns a real property failure into a
spurious flake.
"""

from __future__ import annotations

import math
from datetime import UTC, datetime
from pathlib import Path

from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from nearmiss.config import Config
from nearmiss.geometry import haversine_m
from nearmiss.models import Report
from nearmiss.pipeline.dedupe import dedupe
from nearmiss.stats.getis_ord import getis_ord_star
from nearmiss.stats.rates import poisson_ci, rate_with_ci, wilson_ci

# A generous-but-finite deadline-free profile shared by every property below.
_SETTINGS = settings(deadline=None, max_examples=200)

# --- shared strategies ------------------------------------------------------

_finite = st.floats(allow_nan=False, allow_infinity=False, min_value=0.0, max_value=1.0e4, width=64)
# z-multipliers for the confidence intervals: strictly positive, bounded so the
# Byar cube-root form stays in its well-behaved regime.
_z = st.floats(min_value=0.5, max_value=5.0, allow_nan=False, allow_infinity=False)


@st.composite
def _layout(draw: st.DrawFn) -> tuple[dict[str, float], dict[str, tuple[float, float]]]:
    """A (values, centroids) pair with matching ids, 3-30 points.

    Centroids are spread over a small lat/lon patch so the fixed band below
    produces a non-trivial mix of in-band and out-of-band neighbors.
    """
    n = draw(st.integers(min_value=3, max_value=30))
    ids = [f"s{i}" for i in range(n)]
    values = {sid: draw(_finite) for sid in ids}
    lats = draw(
        st.lists(
            st.floats(min_value=-0.01, max_value=0.01, allow_nan=False, allow_infinity=False),
            min_size=n,
            max_size=n,
        )
    )
    lons = draw(
        st.lists(
            st.floats(min_value=-0.01, max_value=0.01, allow_nan=False, allow_infinity=False),
            min_size=n,
            max_size=n,
        )
    )
    centroids = {sid: (lats[i], lons[i]) for i, sid in enumerate(ids)}
    return values, centroids


def _band_neighbors(
    centroids: dict[str, tuple[float, float]], band_m: float
) -> dict[str, set[str]]:
    """Fixed straight-line-band neighborhood for exercising getis_ord_star.

    The production pipeline builds neighborhoods from the street network
    (FIX-02, nearmiss.network.SegmentGraph); these metamorphic tests only need
    SOME fixed neighborhood structure, so a centroid distance band keeps the
    fixtures self-contained.
    """
    ids = list(centroids)
    return {
        a: {
            b
            for b in ids
            if b != a
            and haversine_m(centroids[a][0], centroids[a][1], centroids[b][0], centroids[b][1])
            <= band_m
        }
        for a in ids
    }


_BAND_M = 500.0


# --- rates: linearity in `per` ---------------------------------------------


@_SETTINGS
@given(
    count=st.integers(min_value=0, max_value=5000),
    exposure=st.floats(min_value=1.0, max_value=1.0e6, allow_nan=False, allow_infinity=False),
    per=st.floats(min_value=1.0, max_value=1.0e5, allow_nan=False, allow_infinity=False),
)
def test_rate_scales_linearly_with_per(count: int, exposure: float, per: float) -> None:
    """Doubling the `per` basis exactly doubles the rate and both CI bounds."""
    rate1, lo1, hi1 = rate_with_ci(count, exposure, per=per)
    rate2, lo2, hi2 = rate_with_ci(count, exposure, per=2.0 * per)
    assert math.isclose(rate2, 2.0 * rate1, rel_tol=1e-9, abs_tol=1e-9)
    assert math.isclose(lo2, 2.0 * lo1, rel_tol=1e-9, abs_tol=1e-9)
    assert math.isclose(hi2, 2.0 * hi1, rel_tol=1e-9, abs_tol=1e-9)


# --- rates: scaling exposures scales the rate by 1/c -----------------------


@_SETTINGS
@given(
    count=st.integers(min_value=0, max_value=5000),
    exposure=st.floats(min_value=1.0, max_value=1.0e5, allow_nan=False, allow_infinity=False),
    c=st.floats(min_value=0.1, max_value=10.0, allow_nan=False, allow_infinity=False),
)
def test_rate_scales_inversely_with_exposure(count: int, exposure: float, c: float) -> None:
    """Scaling the exposure denominator by c scales the rate by 1/c."""
    base, _, _ = rate_with_ci(count, exposure)
    scaled, _, _ = rate_with_ci(count, exposure * c)
    assert math.isclose(scaled, base / c, rel_tol=1e-9, abs_tol=1e-9)


# --- Gi*: scale invariance of the z-scores ---------------------------------


@_SETTINGS
@given(
    layout=_layout(),
    c=st.floats(min_value=0.01, max_value=100.0, allow_nan=False, allow_infinity=False),
)
def test_getis_ord_scale_invariant(
    layout: tuple[dict[str, float], dict[str, tuple[float, float]]], c: float
) -> None:
    """Multiplying every value by a constant c leaves the Gi* z-scores unchanged.

    This is the metamorphic form of exposure re-scaling: scaling all exposures
    by c scales every rate by 1/c, and a standardized statistic like Gi* is
    invariant to that common factor.
    """
    values, centroids = layout
    neighbors = _band_neighbors(centroids, _BAND_M)
    base = getis_ord_star(values, neighbors)
    scaled = getis_ord_star({k: v * c for k, v in values.items()}, neighbors)
    assert base.keys() == scaled.keys()
    for k in base:
        assert math.isclose(base[k], scaled[k], rel_tol=1e-9, abs_tol=1e-9)


# --- Gi*: insertion-order independence --------------------------------------


@_SETTINGS
@given(layout=_layout(), data=st.data())
def test_getis_ord_permutation_invariant(
    layout: tuple[dict[str, float], dict[str, tuple[float, float]]], data: st.DataObject
) -> None:
    """Permuting the dict insertion order leaves getis_ord_star output unchanged."""
    values, centroids = layout
    keys = list(values.keys())
    order = data.draw(st.permutations(keys))
    perm_values = {k: values[k] for k in order}
    perm_centroids = {k: centroids[k] for k in order}
    base = getis_ord_star(values, _band_neighbors(centroids, _BAND_M))
    permuted = getis_ord_star(perm_values, _band_neighbors(perm_centroids, _BAND_M))
    assert base.keys() == permuted.keys()
    for k in base:
        assert math.isclose(base[k], permuted[k], rel_tol=1e-12, abs_tol=1e-12)


# --- Gi*: numerical-hardening witness --------------------------------------


@_SETTINGS
@given(
    offset=st.floats(min_value=1.0e6, max_value=1.0e9, allow_nan=False, allow_infinity=False),
)
def test_getis_ord_survives_large_common_offset(offset: float) -> None:
    """A large common offset with a tiny spread still yields finite, sane z-scores.

    Gi* is shift-invariant, so the exact hand-computed layout from
    test_stats_numerics.py (z = ±sqrt(3)) must reproduce those values even when
    every value is lifted onto a ~1e8 pedestal. The old one-pass variance
    (E[x^2] - E[x]^2) catastrophically cancels at this magnitude — the two
    ~1e16 terms differ only in digits already lost to rounding, so variance
    collapses to <= 0, s becomes 0.0, and every z-score is silently zeroed.
    The two-pass variance keeps the arithmetic at the scale of the true spread.
    """
    values = {
        "A": offset + 2.0,
        "B": offset + 2.0,
        "C": offset + 0.0,
        "D": offset + 0.0,
    }
    centroids = {
        "A": (0.0, 0.0),
        "B": (0.0, 0.002),
        "C": (0.0, 1.0),
        "D": (0.0, 1.002),
    }
    z = getis_ord_star(values, _band_neighbors(centroids, 300.0))
    assert all(math.isfinite(v) for v in z.values())
    # The variance did not collapse: the hot/cold structure is preserved.
    assert z["A"] > 0.0 > z["C"]
    assert math.isclose(z["A"], math.sqrt(3.0), rel_tol=1e-6, abs_tol=1e-6)
    assert math.isclose(z["C"], -math.sqrt(3.0), rel_tol=1e-6, abs_tol=1e-6)


# --- poisson_ci: ordering, non-negativity, containment, monotone widening ---


@_SETTINGS
@given(count=st.integers(min_value=0, max_value=10000), z=_z)
def test_poisson_ci_structural(count: int, z: float) -> None:
    """Bounds are ordered, non-negative, and contain the point estimate (count)."""
    low, high = poisson_ci(count, z)
    assert low >= 0.0
    assert low <= high
    assert low <= count <= high + 1e-9


@_SETTINGS
@given(
    count=st.integers(min_value=0, max_value=10000),
    z1=_z,
    z2=_z,
)
def test_poisson_ci_widens_monotonically(count: int, z1: float, z2: float) -> None:
    """A larger z never narrows the interval (lower falls, upper rises)."""
    if z1 > z2:
        z1, z2 = z2, z1
    low1, high1 = poisson_ci(count, z1)
    low2, high2 = poisson_ci(count, z2)
    assert low2 <= low1 + 1e-9
    assert high2 >= high1 - 1e-9


# --- wilson_ci: bounds stay within [0, 1] -----------------------------------


@_SETTINGS
@given(data=st.data(), z=_z)
def test_wilson_ci_within_unit_interval(data: st.DataObject, z: float) -> None:
    """Wilson score bounds are a valid probability interval in [0, 1]."""
    trials = data.draw(st.integers(min_value=1, max_value=100000))
    successes = data.draw(st.integers(min_value=0, max_value=trials))
    low, high = wilson_ci(successes, trials, z)
    assert 0.0 <= low <= high <= 1.0


# --- dedupe: order independence --------------------------------------------


def _config(**overrides: object) -> Config:
    base: dict[str, object] = {
        "city": "Test",
        "streets_path": Path("unused"),
        "reports_path": Path("unused"),
        "exposure_path": Path("unused"),
        "raw_dir": Path("unused"),
        "out_dir": Path("unused"),
    }
    base.update(overrides)
    return Config(**base)  # type: ignore[arg-type]


@st.composite
def _reports(draw: st.DrawFn) -> list[Report]:
    n = draw(st.integers(min_value=1, max_value=12))
    base_ts = datetime(2026, 1, 1, tzinfo=UTC).timestamp()
    reports: list[Report] = []
    for i in range(n):
        dlat = draw(st.floats(min_value=-0.01, max_value=0.01, allow_nan=False))
        dlon = draw(st.floats(min_value=-0.01, max_value=0.01, allow_nan=False))
        dt = draw(st.floats(min_value=0.0, max_value=3600.0, allow_nan=False))
        token = draw(st.sampled_from(["tok-a", "tok-b", ""]))
        hazard = draw(st.sampled_from(["close_pass", "left_hook", "dooring"]))
        reports.append(
            Report(
                id=f"r{i}",
                occurred_at=datetime.fromtimestamp(base_ts + dt, tz=UTC).isoformat(),
                lat=34.0522 + dlat,
                lon=-118.2437 + dlon,
                mode="cyclist",
                hazard_type=hazard,
                severity="near_miss",
                reporter_token=token,
            )
        )
    return reports


@settings(deadline=None, max_examples=150, suppress_health_check=[HealthCheck.too_slow])
@given(reports=_reports(), data=st.data())
def test_dedupe_order_independent(reports: list[Report], data: st.DataObject) -> None:
    """dedupe() is a pure function of the report *set*, not their input order."""
    config = _config()
    kept_a, removed_a = dedupe(list(reports), config)
    permuted = data.draw(st.permutations(reports))
    kept_b, removed_b = dedupe(list(permuted), config)
    # Deterministic chrono ordering means the kept lists are identical, not just
    # equal as sets; removed-id sets must match too.
    assert [r.id for r in kept_a] == [r.id for r in kept_b]
    assert set(removed_a) == set(removed_b)
