"""The benchmark suite has to be what its generator and scorer produce, and the
scorecard document has to be what the scorecards say.

`benchmarks/` ships 36 committed files and 24 of them were held to the code.
`tests/test_benchmark_suite.py` regenerates each city's four data files, which is the
real reason nothing has drifted; its `FROZEN_FILES` tuple omits `config.toml`, so six
generated city configs were regenerated by nothing. It re-scores exactly one city, so
five of the six `scorecard.json` files were regenerated by nothing. `make
bench-suite-verify` never runs the scorer, and no CI job and no `make` prerequisite has
ever run `bench-suite-verify` at all.

And `benchmarks/SCORECARD.md` says, in its own opening sentence, that its numbers "are
copied from the committed `benchmarks/cities/*/scorecard.json`" -- by hand, with nothing
recomputing them. That is the wildfire-README shape: correct today, correct only until
someone re-runs something.

`tools/bench_check.py` regenerates the whole suite into a temporary directory, so the
committed copies are never overwritten by the check that is about to read them, and
enumerates rather than lists. These tests hold it to failing.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
from tools import bench_check

ROOT = Path(__file__).resolve().parents[1]
MAKEFILE = ROOT / "Makefile"


def test_every_committed_benchmark_file_is_covered_by_this_gate() -> None:
    """The denominator, named: nothing under benchmarks/cities may be invisible."""
    names = bench_check.regimes()
    assert names, "benchmarks/configs defines no regime"
    committed = set(bench_check._files(bench_check.CITIES))
    expected = {
        f"{name}/{filename}"
        for name in names
        for filename in (
            "config.toml",
            "exposure.json",
            "ground_truth.json",
            "reports.json",
            "scorecard.json",
            "streets.geojson",
        )
    }
    excluded = {name for name, _ in bench_check.NOT_REGENERATED}
    assert committed - expected - excluded == set(), (
        "a committed benchmark file is neither regenerated by this gate nor excluded"
    )


def test_the_published_table_states_the_committed_scores() -> None:
    """`make bench-check`, on the document that says it copied these numbers by hand."""
    assert bench_check.check_table(bench_check.regimes()) == []


def test_a_wrong_figure_in_the_table_is_caught(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Tamper with one cell in a copy and require the check to name it."""
    tampered = tmp_path / "SCORECARD.md"
    text = bench_check.SCORECARD.read_text(encoding="utf-8")
    edited = re.sub(r"^\| baseline \| 80% \|", "| baseline | 95% |", text, count=1, flags=re.M)
    assert edited != text, "the results table no longer carries the baseline recall row"
    tampered.write_text(edited, encoding="utf-8")

    monkeypatch.setattr(bench_check, "SCORECARD", tampered)
    problems = bench_check.check_table(bench_check.regimes())
    assert any("baseline Recall = 95%" in problem for problem in problems), problems


def test_a_row_that_disappears_from_the_table_is_caught(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A check that quietly covers one regime fewer is a check that stopped checking."""
    tampered = tmp_path / "SCORECARD.md"
    text = bench_check.SCORECARD.read_text(encoding="utf-8")
    edited = re.sub(r"^\| maup_coarse \|.*\|\n", "", text, count=1, flags=re.M)
    assert edited != text
    tampered.write_text(edited, encoding="utf-8")

    monkeypatch.setattr(bench_check, "SCORECARD", tampered)
    problems = bench_check.check_table(bench_check.regimes())
    assert any("maup_coarse" in problem for problem in problems), problems


def test_a_rate_with_no_denominator_is_written_the_way_the_table_writes_it() -> None:
    """`scorer.py` writes `null` where precision has no denominator; the table says n/a."""
    assert bench_check._as_written(None) == "n/a"
    assert bench_check._as_written(0.3636) == "36%"
    assert bench_check._as_written(0.0) == "0%"


def test_the_generator_can_write_outside_the_repository(tmp_path: Path) -> None:
    """The property that lets a gate regenerate without overwriting what it compares."""
    from benchmarks import generator

    cfg = generator.RegimeConfig.from_json(bench_check.CONFIGS / "baseline.json")
    written = generator.write_city(cfg, tmp_path)
    assert written == tmp_path / "baseline"
    committed = bench_check.CITIES / "baseline" / "streets.geojson"
    assert (written / "streets.geojson").read_bytes() == committed.read_bytes()
    assert not (tmp_path / "baseline" / "scorecard.json").exists()


def test_the_committed_scorecards_parse_as_the_gate_reads_them() -> None:
    """Every field the table binds must exist in every scorecard, or the bind is empty."""
    for name in bench_check.regimes():
        card = json.loads(
            (bench_check.CITIES / name / "scorecard.json").read_text(encoding="utf-8")
        )
        for _, field in bench_check.TABLE_COLUMNS:
            assert field in card, f"{name}/scorecard.json has no {field}"


def test_bench_check_is_a_prerequisite_of_make_verify() -> None:
    """`bench-suite-verify` existed for months and no target and no CI job ever ran it."""
    recipe = re.search(r"^verify:([^\n]*)", MAKEFILE.read_text(encoding="utf-8"), re.MULTILINE)
    assert recipe, "the Makefile no longer defines a `verify` target"
    assert "bench-check" in recipe.group(1).split("##")[0].split(), (
        "`make verify` no longer runs `bench-check`, so nothing a contributor runs holds "
        "the committed benchmark suite to the code that produces it"
    )
