#!/usr/bin/env python3
"""Rebuild the planted-truth benchmark suite into a temporary directory and compare,
and hold `benchmarks/SCORECARD.md`'s table to the scorecards it says it copied.

`benchmarks/` ships 36 committed files. What was actually held to the code was 24 of
them, and the gap was not where the target names suggest.

* `make bench-suite-verify` regenerates the cities in the working tree and diffs. No CI
  job and no `make` prerequisite has ever invoked it, so it is a gate nothing asks.
* `tests/test_benchmark_suite.py` does cover the four data files of every city
  (`test_frozen_city_matches_generator`), which is the real reason the suite has not
  drifted. Its `FROZEN_FILES` tuple omits `config.toml`, so the generated city config
  was regenerated by nothing, in six cities.
* `test_scorer_recovers_the_baseline_scorecard` re-scores exactly one city. The other
  five `scorecard.json` files -- `reporting_bias`, `overdispersion`, `exposure_error`,
  `maup_fine`, `maup_coarse` -- were regenerated by nothing, and `bench-suite-verify`
  does not run the scorer, so its diff could not have noticed them either.
* `benchmarks/SCORECARD.md` opens by saying "The numbers below are copied from the
  committed `benchmarks/cities/*/scorecard.json`". Copied by hand, checked by nothing.
  That is the same shape as a README quoting figures out of a published measurements
  file: correct today, and correct only for as long as nobody re-runs anything.

This closes all of it, by enumerating rather than listing. `generator.py --out` and
`scorer.py --out` write into a temporary tree, so the committed copies are never
overwritten by the check that is about to read them, and every regenerated file is
byte-compared. The published tree is
then enumerated: a file under `benchmarks/cities/` that this gate neither regenerates
nor documents an exclusion for is a failure, so a new artifact is covered or it stops
the build. Finally every numeric cell of SCORECARD.md's results table is re-derived
from the committed scorecards, in both directions -- a regime the table stopped
publishing fails too, because a row that quietly disappears makes this check smaller
than it looks.

    python tools/bench_check.py

Exit: 0 when the suite regenerates byte-for-byte and the table states the scores; 1
otherwise. No network. Nothing is ever written inside the repository.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
BENCHMARKS = ROOT / "benchmarks"
CITIES = BENCHMARKS / "cities"
CONFIGS = BENCHMARKS / "configs"
SCORECARD = BENCHMARKS / "SCORECARD.md"

#: Files under `benchmarks/cities/` that neither producer writes, each with the reason
#: it cannot be regenerated. Empty today, and deliberately kept as the only way past the
#: enumeration below: a new committed benchmark artifact is either regenerated and
#: compared, or it appears here with a written reason. It cannot pass by being invisible.
NOT_REGENERATED: tuple[tuple[str, str], ...] = ()

#: SCORECARD.md's results table, column label -> the scorecard field it publishes.
#: Percentages, rounded to whole numbers, exactly as the table writes them.
TABLE_COLUMNS: tuple[tuple[str, str], ...] = (
    ("Recall", "hotspot_recall"),
    ("Precision", "hotspot_precision"),
    ("Decoy FP", "decoy_exposure_fp_rate"),
    ("Bias trap", "reporting_bias_trap_rate"),
    ("Background FP", "background_fp_rate"),
    ("CI coverage", "interval_coverage"),
)

#: What the table writes where a rate has no denominator. `scorer.py` writes `null`.
NOT_APPLICABLE = "n/a"


def _run(argv: list[str]) -> None:
    completed = subprocess.run(argv, cwd=ROOT, capture_output=True, text=True, check=False)
    if completed.returncode != 0:
        raise RuntimeError(
            f"{' '.join(argv[1:])} exited {completed.returncode}\n"
            f"{completed.stdout}\n{completed.stderr}"
        )


def regimes() -> list[str]:
    """Every regime the suite defines, read off `benchmarks/configs/`."""
    return sorted(path.stem for path in CONFIGS.glob("*.json"))


def rebuild(work: Path, names: list[str]) -> None:
    """Regenerate every city and every scorecard under `work`, never under `benchmarks/`."""
    _run([sys.executable, str(BENCHMARKS / "generator.py"), "--out", str(work)])
    for name in names:
        _run(
            [
                sys.executable,
                str(BENCHMARKS / "scorer.py"),
                "--city",
                name,
                "--out",
                str(work / name),
            ]
        )


def _files(directory: Path) -> list[str]:
    return sorted(
        str(path.relative_to(directory))
        for path in directory.rglob("*")
        if path.is_file() and not path.is_symlink()
    )


def compare(work: Path) -> tuple[list[str], list[str]]:
    """Return `(problems, matched)` for the regenerated suite against the committed one."""
    problems: list[str] = []
    matched: list[str] = []
    regenerated = set(_files(work))

    for relative in sorted(regenerated):
        committed = CITIES / relative
        if not committed.is_file():
            problems.append(
                f"benchmarks/cities/{relative}: regenerated and not committed. Run "
                "`make bench-suite` and commit the result."
            )
            continue
        if committed.read_bytes() != (work / relative).read_bytes():
            problems.append(
                f"benchmarks/cities/{relative}: the committed file is not what the code "
                "produces. Regenerate it and commit the result; never edit it by hand."
            )
        else:
            matched.append(relative)

    for relative in _files(CITIES):
        if relative in regenerated:
            continue
        reason = next(
            (reason for name, reason in NOT_REGENERATED if name == relative),
            None,
        )
        if reason is None:
            problems.append(
                f"benchmarks/cities/{relative}: committed and regenerated by nothing. Add it "
                "to this gate, or record why it cannot be regenerated."
            )
    return problems, matched


# ---------------------------------------------------------------------------
# The prose the suite publishes about itself.
# ---------------------------------------------------------------------------

_ROW = re.compile(r"^\|\s*(?P<regime>[a-z_]+)\s*\|(?P<cells>.+)\|\s*$", re.MULTILINE)


def published_table() -> dict[str, list[str]]:
    """Every data row of SCORECARD.md's results table, cells exactly as written."""
    rows: dict[str, list[str]] = {}
    for match in _ROW.finditer(SCORECARD.read_text(encoding="utf-8")):
        cells = [cell.strip() for cell in match.group("cells").split("|")]
        rows[match.group("regime")] = [cell for cell in cells if cell]
    return rows


def _as_written(value: Any) -> str:
    """One scorecard rate, formatted the way the table writes it."""
    if value is None:
        return NOT_APPLICABLE
    return f"{round(float(value) * 100)}%"


def check_table(names: list[str]) -> list[str]:
    """Hold every cell of the published table to the committed scorecards, both ways."""
    problems: list[str] = []
    published = published_table()

    orphaned = sorted(set(published) - set(names))
    if orphaned:
        problems.append(
            f"benchmarks/SCORECARD.md publishes rows for regimes the suite does not "
            f"define: {orphaned}"
        )
    missing = sorted(set(names) - set(published))
    if missing:
        problems.append(
            f"benchmarks/SCORECARD.md no longer publishes a row for {missing}. A row that "
            "disappears makes this check smaller than it looks, so it fails here."
        )

    for name in sorted(set(names) & set(published)):
        card = json.loads((CITIES / name / "scorecard.json").read_text(encoding="utf-8"))
        cells = published[name]
        if len(cells) != len(TABLE_COLUMNS):
            problems.append(
                f"benchmarks/SCORECARD.md row {name!r} has {len(cells)} cells and this gate "
                f"knows {len(TABLE_COLUMNS)} columns; a cell it cannot read is a cell it "
                "cannot check"
            )
            continue
        for (label, field), written in zip(TABLE_COLUMNS, cells, strict=True):
            expected = _as_written(card[field])
            if written != expected:
                problems.append(
                    f"benchmarks/SCORECARD.md says {name} {label} = {written}; "
                    f"{name}/scorecard.json says {field} = {expected}"
                )
    return problems


def report() -> int:
    names = regimes()
    if not names:
        print(
            "bench-check FAILED: benchmarks/configs/ defines no regime; an empty suite must "
            "not report that every benchmark reproduces",
            file=sys.stderr,
        )
        return 1

    with tempfile.TemporaryDirectory(prefix="nearmiss-bench-") as name:
        work = Path(name)
        try:
            rebuild(work, names)
        except RuntimeError as error:
            print(f"bench-check FAILED: {error}", file=sys.stderr)
            return 1
        problems, matched = compare(work)

    problems += check_table(names)
    if not matched:
        problems.append(
            "no benchmark artifact was regenerated and compared; an empty run must not "
            "report that the suite reproduces"
        )

    if problems:
        print("\nbench-check FAILED:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    print(
        f"bench-check: {len(matched)} benchmark files across {len(names)} regimes "
        "regenerated into a temporary directory and byte-identical to the committed bytes; "
        "every figure in benchmarks/SCORECARD.md's table equals the scorecard it quotes."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(report())
